### ISSUE TITLE
Wrong error messages on production with local dev

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#128]
**User story**

As a developer
I want to get clear error messages
so that I know which errors/bugs or messages are relevant. 

---

**Definition of done**

- [ ] investigate and fix why we get production alerts when an error happens localy

---

**Technical details**

_Backend_

- [ ] investigate why is Sentry enabled in development and turn off.

Error message in Slack devbots:

```
Sentry (production) APP

RuntimeError: Note: warnings/errors about extension ownership can safely be ignored.
Culprit
----------------
heroku:update_db:staging

Project
----------------
app82955581@heroku.com buzzn-core-production



[16:34] 
RuntimeError: Command failed with status (1): [heroku pg:reset --remote=staging...]
Culprit
----------------
heroku:update_db:staging

Project
----------------
app82955581@heroku.com buzzn-core-production
```

**Comment by evaklopp** [comment]
@phillipoertel please help with DoDs aswell. I´cant imagine what is the solution. Thanks.

**Comment by phillipoertel** [comment]
I could fix that by removing SENTRY_DSN from my .env.local. By design the sentry-raven gem reports errors as soon as that env variable is set, no matter which environment.

I still don't understand why the sentry-raven gem is required in development though. It is installed because `bundle install` installs all gems regardless of groups. But our `Bundler.require(:default, Rails.env)` in https://github.com/buzzn/core/blob/better-pho-create-task/config/application.rb#L14 only requires global gems (:default option) and those for the current environment. Ignoring since it's not worth investigating right now.
