### ISSUE TITLE
deduplicate PT customer data

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#132]
**PRs**
https://github.com/buzzn/core/pull/1370
https://github.com/buzzn/core/pull/1372

---

**User story**
As PhO
I want for each real life customer I want only have one record in the system. 

---

**Definition of done**

- [x] all duplication cases based on email and phonenumber have been reviewed 
- [x] a real life customer exists only once in our system
- [x] define the rules. within role like PT, PG, organisation the person/organisation exists only once
- [x] timeboxed task: 4 hours

---
**XD**

What happens, if a person has more than one role? All combination of roles are possible. 

**Technical details**

- [x] deduplicate group owners, fix missing owner on organizations (Cohaus/Traudl Brumbauer)
- [x] deduplicate group owners (which come from `buzzndb.kontakt_acc`) and powertakers (from `minipooldb.kontaktdaten`). Examples: 
  - [x] Willi Kral, https://goo.gl/gUSooD -- PhO fixes it by setting same email address for both
  - [x] Warnke, https://goo.gl/uQZqm9 (btw, he's also in the organizations table) -- PhO fixes it by setting same name address for both
  - [x] Traudl Brumbauer (owner of many localpools, but created twice)
- [x] duplicate organizations? (same email, but separate records) VRD, Erdle, Eiser, Ritter: https://github.com/buzzn/scrum/issues/130#issuecomment-358971519
- [x] emails that we now have on both org and person tables (excluding organizations which have market roles):
  - [x] a.bock@ich-hab-bock.de
  - [x] a.heinrich@weissflogheinrich.de
  - [x] al@leonhardarchitekten.de
  - [x] bad_sulz@kabelmail.de
  - [x] bauwesen@hallbergmoos.de
  - [x] buero@wagnis.org
  - [x] erdlekh@erdlekh.de
  - [x] info@BEG-FS.de
  - [x] info@christoph-eiser.de
  - [x] m.schabl@isarwatt.de
  - [x] mail@hgschreck.de
  - [x] mar_s1@gmx.de
  - [x] mattauch@beg-remstal.de
  - [x] ssge@telta.de
  - [x] t.brumbauer@wogeno.de
  - [x] team@thies-hahn.de
  - [x] tim.warnke@gmx.de
  - [x] ulrich.haushofer@gmx.de
  - [x] Ralf.schroeder@gmail.com
- [x] same for phone numbers. Fix emails first though as the cases are likely the same

**Comment by phillipoertel** [comment]
Localpool owners and contact persons  are now all imported correctly and uniquely:

[localpool owners and contact persons.pdf](https://github.com/buzzn/scrum/files/1682160/localpool.owners.and.contact.persons.pdf)

**Comment by evaklopp** [comment]
cool, just checked your pdf. looks good! Can I do anything else to check the data than seeing in your pdf that there are no more duplicates?

**Comment by dottorer** [comment]
@phillipoertel Awesome job, this is not trivial and quite tedious to untangle. Thanks for staying on it til the end.

**Comment by phillipoertel** [comment]
@evaklopp @dottorer it’s best if PhIlipp does the checking for duplicates. Philipp knows the data, and how it should be fixed, and might spot other problems in the process. To do so, look at the power taker contracts of each localpool, and make sure that: 

- if one power taker has multiple contracts, make sure that the person (or organization) is always the same. It’s quickest to just check the id in the link (hover over link to see it in the browser’s status bar), without opening the page itself

- same procedure for the contractor of each contract. 

- if the group owner has one or more contracts, make sure that they also have the same link/id. 

It’s not ideal that he won’t be able to do that in the next 2-3 weeks. To be honest I‘m not confident that everything we imported is „done“, I don’t think PhO has given our work a serious look so far. It‘s disappointing not to get real customer feedback, and since the import is complex, I don’t look forward to fixing the nitty gritty details weeks after I implemented them — the longer a bug has existed, the longer it takes to fix it. 
But of course I know Philipp has other things to do right now and is planning to check this after the 2017 billing.

**Comment by phillipoertel** [comment]
I (accidentally) found some more duplicates after an uniqueness constraint on the email field was added. There are two cases:

1. two different people use the same email address => no way to fix this

anne-tobi@gmx.de
ulrich.haushofer@gmx.de
globaltrading@t-online.de

2. Same person where the name is spelled differently => this should be fixed beekeeper by using the same first name, then they will be merged automatically

siegmar.moench@gmx.de
tim.warnke@gmx.de

**Comment by evaklopp** [comment]
Thank you @phillipoertel for your amazing patience and work so far! I understand your disappointment - but at that moment I can´t do nothing about it. As soon PhO has finished his current tasks, I ask him to check the data. But I´m sure that you´ve done the most of it! So from my current PO-domain, I would accept the story as it is so far. @dottorer any objections? You or me have to tell PhO.

**Comment by mkristian** [comment]
@phillipoertel the first of your points you solved already by allowing two persons sharing the same email address. what the second point ? does @dottorer knows to these two to @pho ?

**Comment by evaklopp** [comment]
I´, accepting this story, keeping in mind that PhO needs to deep dive into the new system data and check. Great job and awsome patience @phillipoertel!
