### ISSUE TITLE
As PhO I want to see all the details of the register 1

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#47]
**PR**
- https://github.com/buzzn/admin-app/pull/249
- https://github.com/buzzn/core/pull/1303
---
**Story**
As PhO I want to see all the details of a register. 

---
**XD prep**

- [x] register detail page: https://invis.io/DXENKK1BK#/265812600_Desktop_HD_-_System_-_Register_Details
- [x]  update design without the excluded fields

exluded, but future: 
- show for all non private/non consumption registers the current power in watt on the top of the register detail page. 
- Readings
- edit/update

---

**DoD**

- [x] register details
- [x] import register detail data
- [x] ~~all fields are displayed according to design.~~

exclude: 
- virtual meter information
- readings
- contract
- devies
- observer

---

**Technical details**

_Frontend_

- [x] show these attributes: 
  - [x] name
  - [x] direction
  - [x] label
  - [x] meter
  - [x] metering point id
  - [x] low load ability
  - [x] obis
  - [x] share publicly
  - [x] share with group

_Backend_

- [x] map/import metering point id
- [x] map/import low load ability
- [x] map/import obis
- [x] map/import share attributes

---

**Beekeeper Mapping Infos**

https://buzzn-team.atlassian.net/wiki/x/OIAZBg
Source tables:
- [msb_gerät](https://buzzn-team.atlassian.net/wiki/download/attachments/102334520/msb_ger%C3%A4t.xlsx?version=5&modificationDate=1511603138337&cacheVersion=1&api=v2)
- [msb_zählwerk_daten](https://buzzn-team.atlassian.net/wiki/download/attachments/102334520/msb_z%C3%A4hlwerk_daten.xlsx?version=4&modificationDate=1511603137307&cacheVersion=1&api=v2)

Data value mapping:
- https://buzzn-team.atlassian.net/wiki/x/mAAq

**Comment by dottorer** [comment]
@evaklopp @eharit I added some comments for the register detail page design. Let's chat today on these items...

**Comment by eharit** [comment]
@evaklopp the screen has been updated, the sections excluded from this iteration are still there but greyed out, all unnecessary fields have been removed, boolean fileds have been replaced with switches. Please review.

**Comment by mkristian** [comment]
@eharit "Last Observed" is highly technical  DB filed which is used to tack the observable to decide when to trigger the next notification - nothing which will be exposed by our API and is only used by our (future) cron job.

**Comment by mkristian** [comment]
@dottorer the `share_with_group` and `share_publicy` - I wonder if the second implies the first, or the otherway around it makes no sense to `share_publicy` but not to `share_with_group`. or is it possible to that both are independent as well in their meaning ?

cc/ @scsirdx

**Comment by phillipoertel** [comment]
@evaklopp @dottorer @eharit s discussed, please add a new user story with the refinements discussed with PhO yesterday; won't change this ticket since it's already in the sprint.

**Comment by phillipoertel** [comment]
@evaklopp could you clarify with PhO if the "low load ability" is a field that we need to keep in the database? Right now we have 1.105 registers in beekeeper. All of them are labeled as not having low load ability. Do we expect to have registers at some point that do have that ability? If we can drop this field, it would simplify the code we need to write for import, show and edit, and of course the XD as well.

I'm also asking not just for this field in particular -- I think we have several cases where we drag along data that isn't really useful. Since we're migrating all data to a new system, we have the opportunity to simplify.

**Comment by dottorer** [comment]
@phillipoertel I discussed this with Stefan as well. Today we only use EasyMeters and their model are low load. In future Stefan can see us using other, different meters which could be medium load or high load even. So for now, we do not need it, but in reality it is a viable property.

How do you want to handle such a scenario? Hide in UI, but keep in model as empty / keep with low_load only? Or remove from model?

**Comment by evaklopp** [comment]
@dottorer @phillipoertel I asked PhO this question yesterday in the evening, and his answer was more or less the same like Stefans. We will need it a soon as we have different meters with medium or high load. We can easily drop it from UI, as long as PhO knows that all the meters are low load. For the Backend I can´t say what is less effort: not to carry it now but add it later or just keep it because it is there. 
According to the data we carry around, we should use this opportunity to get rid of useless data, which I can check when I talk to PhO. But I think @dottorer did a lot of it already? And is more into this topic?

**Comment by phillipoertel** [comment]
@evaklopp 

Some stats from beekeeper: the first localpool is from 2002. we have a total of 47 localpools and ~1000 registers, all of them with the same low load ability. So IMHO: if the business strategy and type of localpools we get won't change fundamentally, there won't be any medium/high load meters any time soon.

PhO and Stefan say we could need it. I __assume__ it's because they would like to be able to represent any kind of setup/meter in our system, not because we will actually need it soon. Otherwise they'd tell you with more certainty. Do they think we'll need that in the next year?

Again, I hope you understand that I'm not arguing about this field in particular, but the general rule: you win a lot of time, and get a useful product to the market sooner if you don't do up front work that has no immediate benefit. 

Often you can split user stories like this as well. Rather than aiming for completeness, 80% percent of the value can often be implemented in 20% of the time/effort.

The only case where it would make sense to add fields/features now is: you expect buzzn not to have any developers at some point in the future, so it would be impossible to add something later on.

So following the YAGNI rule (http://c2.com/xp/YouArentGonnaNeedIt.html) I would suggest to remove all code and features that is/are
1. uncertain if needed that for the envisioned "localpool admin" product
2. easy to recreate or restore (all of it is since we're using version control)

**Comment by evaklopp** [comment]
Yipiiiyayey

**Comment by mkristian** [comment]
I am totally confused - there is an open PR on this issue - not merged or at least not closed but this issue is closed.

**Comment by phillipoertel** [comment]
You are right Christian, I moved the ticket to testing too early. We still need to fix the associations and review the PR.

**Comment by evaklopp** [comment]
hooray, closing!
