### ISSUE TITLE
As Pho I want to see the register readings

### ISSUE THREAD

**Issue by evaklopp** [buzzn/scrum#66]
**PR**
- https://github.com/buzzn/admin-app/pull/256
- https://github.com/buzzn/core/pull/1317
---
**Story**
As Pho I want to see the register readings
to see the last and historic readings. 

---
**XD**

screen: https://projects.invisionapp.com/d/main#/console/12205665/266641260/preview
 Register Detail page, readings-tab

---
**DoD**

- [x] Import the readings of all registers. 

- [x] Show the last and all historic readings of this register in a list: sorted from top to down: according to the date, last reading on top.

- [x] show the reading in a table which consists of: date/Datum, value/Wert, reason/Grund, status/Status, comment/Anmerkung

excluded: 

-  incompleteness test
-  gap free contract history for each register

---
**technical details**

_Frontend_

- [x] table of readings with cols: date, value (display in kWh), reason
- [x] add missing translations for the reading reason: 
  - https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/8486963/Flow+Add+and+view+register+readings. 
  - Example: `PMR - Turnusablesung`
- [x] add accordion view with: status, quality, read by, comment (comment has no value from the API yet)

_Backend_

Beekeeper stores the register readings in the table `msb_zählwerk_zst`. See https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/102334520/4+-+Data+migration+from+BeeKeeper for details.

- [x] map "ablesezeitpunkt" to our attribute "date", and parse it (we get a string from Beekeeper (BK))
- [x] map "ablesegrund" to reason, make sure to map to correct enum value
- [x] map "qualität" (handle like ablesegrund, also an enum)
- [x] map "ableser" (handle like ablesegrund, also an enum)
- [x] map "statuszst" (handle like ablesegrund, also an enum)
- [x] drop the column raw_reading
- [x] map value: convert to Wh (BK data is in kWh)
- [x] set unit to "Wh"
- [x] if the field`ablesegrund` contains "Gerätewechsel": Add the `zaehlernummer` to the our comment field. Otherwise comment stays empty.

**Comment by evaklopp** [comment]
@scsirdx this is just freshly pressed and reviewed design, ready for you to fill it into the frontend. Did you already talked about it with Pali or do you need any further information?  You´ll find a description in the yellow note nr. 15 in InVision. Please ask if you have more questions.

**Comment by phillipoertel** [comment]
@evaklopp are we going to translate the register labels in the top right as well? It still says "CONSUMPTION", but in the list of registers we now translate the labels.

**Comment by phillipoertel** [comment]
@eva not sure if I should leave comments here or in Invision ...

Regarding the design:
I suggest we add the EDIFACT code to reading details as well, just like we plan to do everywhere else. So Ableser would say "VNB - Verteilnetzbetreiber" in this case.

Same for the value of "Qualität", there it'd be "220 - Abgelesener Wert".

**Comment by evaklopp** [comment]
@phillipoertel 
- Comments: without your InVision comment I would´nt know what your comment is about, so I think it is a good way as long as we talk about design. 
- label consumption top right: yes of course we translate this. 
- EDIFACT: I answered you in InVision ;-) But the most important question is: is there more EDIFACT code than you wrote above?

**Comment by dottorer** [comment]
@evaklopp EDIFACT codes are all tracked here: https://buzzn-team.atlassian.net/wiki/spaces/DEV/pages/2752664/Flow+View+and+Edit+Real+Meters+and+Registers

They stem from the following document: http://www.edi-energy.de/files2/Lesefassung_UTILMD_AHB_Einspeiser_2.0_2013-11-29.pdf

We should show the "code - description" as Philip pointed out, so Pho can reference back to any messages, etc.

**Comment by dottorer** [comment]
Noone assigned to this tics, onyl last DoD not yet checked. Is it ready for testing or what are we missing?

**Comment by phillipoertel** [comment]
@dottorer FYI I added the readings as a "main" resource in the console so we can easily browser/filter them: https://staging-console.buzzn.io/admin/readings

**Comment by evaklopp** [comment]
@scsirdx I did some testing, and here are the results: 

- I don´t see clear headlines of the table: 
![bildschirmfoto 2017-12-12 um 16 05 04](https://user-images.githubusercontent.com/22292464/33891472-51cc070c-df56-11e7-8f74-ec0c9ecf1684.png)

- chevrons of the accordion: please make them point the other way round: if the accordion is closed, the chevron points down. if open, chevron points up

- it wasn´t a DoD so I understand if you neclect to do it, but if it isn´t a big thing I would be pleased: as the readings-tab is the first tab in the tab list, it would be very nice if it is also the first tab which is opened when a user clicks on the reader-names (instead of the details tab). 

Thank you ;-)

**Comment by dottorer** [comment]
@scsirdx @phillipoertel  I did some research to clarify if / how readings are supposed to be left behind in BeeKeeper.

I get the following desired result:
- 102 meters (and their included register)
- 303 readings
are not supposed to be imported since they:
- do not belong to a group
- are for virtual meters

Ugly query used:
```
SELECT * 
FROM minipooldb."msb_zählwerk_zst" rdg

where CONCAT(rdg.vertragsnummer || '/' || rdg.nummernzusatz) IN (
SELECT 

CONCAT(met.vertragsnummer || '/' || met.nummernzusatz) as meter_num

FROM minipooldb."msb_gerät" met
WHERE met.vertragsnummer NOT IN (select grp.messvertragsnummer from minipooldb.minipool_objekte grp where grp.minipool_start <> '0000-00-00') 
OR met.adresszusatz like '%virt%'
OR met."zählernummer"  like '%virt%'
OR met."zählerHersteller"  like '%virt%'
OR met."zählerTyp"  like '%virt%'
OR met."berechnetbeschreibungkurz"  like '%virt%'
OR met."berechneterZähler" = 'Ja')
```

I think this dovetails nicely with the results you were both seeing on meter/register/reading imports.
Also, I was able to craft some queries on the heroku dataclips and compare what comes in for our local groups so far: https://dataclips.heroku.com/jysgjdkbeobrjcionwcofsdcrccf-Group-counts .
I will build this up as we bring in more and more stuff.

**Comment by dottorer** [comment]
@scsirdx Also adding to Eva's feedback, the readings do not seem to sort by date yet:
![image](https://user-images.githubusercontent.com/14217285/33895738-75971ca2-df61-11e7-998f-3e39adc5664e.png)

**Comment by evaklopp** [comment]
Hey @scsirdx despite all the found issues above are solved, still one thing left. It is about the spacing/aligning of the labels in the accordion when opened: 
The labels "Ableser", "Qualität" should align left to the labels above ("Messwert", "Ablesegrund"). See Design-screenshot here: 

![bildschirmfoto 2017-12-13 um 19 06 19](https://user-images.githubusercontent.com/22292464/33954495-c1693d22-e038-11e7-96ec-0ce3e1a76058.png)

link: https://projects.invisionapp.com/d/main#/console/12205665/266641260/preview

**Comment by scsirdx** [comment]
@evaklopp Accordion content is not related to table structure at all. Table is dynamic (and even resizable), accordion block is just an attached div.
In theory it's possible to add table resize events listeners or create our own table from scratch, but each of this actions will increase the size of this ticket.
And before i start, please provide designs for all usecases: when accordion have more/less labels than table columns, when there is different number of accordion labels in different rows, when table column is resized (or initially narrow) but value in related accordion part is long.

**Comment by dottorer** [comment]
I would not invest more time in the alignment of fields in the accordion. To me it is visibly readable and works well as a progressive disclosure of information. Imho not worth our time if we can work on other important things.

**Comment by evaklopp** [comment]
Yeah, closing thanks for the good work!

**Comment by phillipoertel** [comment]
@dottorer I noticed yesterday that the reading's values are stored as the float data type in the DB. Since math on floating point numbers is not precise, we may run into errors later. Example: 0.1 * 0.2 => 0.020000000000000004.

**Comment by phillipoertel** [comment]
@dottorer @evaklopp from the review meeting I remember:
- display all register energy values in `kWh`
- refine the display of the register reading ('Zählerstand'), which is just a number, and the actual measured energy in kWh (which can be != reading because of the converter constant).

Not mentioned, but I think it would be nice to display larger numbers with separators for easier reading. Instead of 1000000, show 1.000.000.

**Comment by mkristian** [comment]
about the float problem.

* float is storage format with 23 significant bits. whether this suitable for our data or not is to be discussed.
* floats are a trade-off in storage size and precision. there are round-off errors and on almost equal number there is cancellation, i.e. the part of the significant which carries the error becomes dominant as the other bits are cancelled out. also it is non-intuitive as subtracting 1 from a big number is just the big number because the significants will not overlap. but if you add up 1s by putting brackets the right way you can reach the big number:
  * `big - (1 + 1 + .... + 1 + 1) = big`
  * `big - (((1+1) + (1+1)) + ((1+1) + (1+1))) ..... = 0`
  * any result between `big` and `0` is possible be ordering the brackets the right way. it is not really the math you learned at school ;) 
* float calculation need an error analysis !
* we are talking about energy and power measurements. as in physics all measurements have an error and that error is it its nature similar to the error a float arithmetic introduce. but in the end you always need to look at you math and need to do an error analysis. for example of such an error discussion: https://github.com/buzzn/core/issues/453#issuecomment-258443205
* databases can store floating point number and integer into the same `Number` type, i.e. oracle does do this. which would be ideal for our purpse. so the storage format has nothing to do with how you do the calculation later on. you always can safely convert your float without loss of significance.
* we a storing our reading as double precision floating point number and I was told by @phillipoertel that this is 'coerced' by active-record to bigdecimal.
* so now it becomes messy, we declare the column as float, AR postgres adapter makes a double out of it and when loading the value it is coerced into a BigDecimal. I have to say this sucks ! I want define my type in ruby and not depend on magic mapping from float -> double -> BigDecimal.
* the `Reading` class uses a a `Number` type which binds a value with a unit and allows arithmetic on this type. Whether I did more than just ensure the units must match on addition and substraction. well multiplying to such values makes not sense as this `W^2h^2` is just non-sense.
