### ISSUE TITLE
As a group owner, I want to label additional registers as 'Common'

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#84]
PR: https://github.com/buzzn/core/pull/1341

---
**Story:**
As a group owner, I want to label additional registers as 'Common' so they show up on the display view.

---

**Definition of done**
- [x] All input registers with the text '%allg%' in the name are labeled CONSUMPTION_COMMON
- [x] input registers of power sources should also be assigned CONSUMPTION_COMMON. 

---
**Technical details**

  _Backend_

- [x] label input registers with "%allg%" as CONSUMPTION_COMMON
- [x] leave existing CONSUMPTION_COMMON assignment as is

**Comment by dottorer** [comment]
@evaklopp @phillipoertel Per discussion with Phil this morning, we could augment our logic to identify more registers for CONSUMPTION_COMMON. This would make the import more valuable and show more registers correctly as 'Allgemeinstrom' on display view. Should be small effort, but requires separate ticket for planning, of course.

**Comment by phillipoertel** [comment]
As just mentioned on slack, input registers of the power sources should also be assigned CONSUMPTION_COMMON. At least some of them still get the label "OTHER" (some examples in the group "UdE 7", the BHKWs).

**Comment by phillipoertel** [comment]
I assigned all meters and updated the staging DB. This results in 77 instead of previously 55 registers with the label CONSUMPTION_COMMON. Compare:

- production: https://console.buzzn.io/admin/registers?utf8=%E2%9C%93&q%5Blabel_in%5D%5B%5D=CONSUMPTION_COMMON&commit=Filter&order=name_asc
- staging: https://staging-console.buzzn.io/admin/registers?utf8=%E2%9C%93&q%5Blabel_in%5D%5B%5D=CONSUMPTION_COMMON&commit=Filter&order=name_asc

I still think we haven't assigned all common registers correctly (what about this one, for example: https://staging-console.buzzn.io/admin/registers/ce3f8c0d-ca73-4be6-a60d-e0eea0e5c52f), but that may be easier to do by hand later on (?)

**Comment by phillipoertel** [comment]
The following groups still have _no_ CONSUMPTION_COMMON registers, it might be worth reviewing them. Some of the registers seem to be common, but please review them in the console.
- Gertrud-Grunow-Straße ("WEG Gem.raum")
- Hühnefeldstraße (Heizung, Aufzug)
- Reinmarplatz (Heizzentrale, E-Tankstelle, UV Haustechnik, Antenne, Aufzug)
- Karmensöldnerstraße (really doesn't seem to have common registers)
- Lindenstraße (really doesn't seem to have common registers)

**Comment by phillipoertel** [comment]
I just noticed the input register of PV Produktion in Reinmarplatz still is labeled OTHER, need to investigate why, tomorrow. Maybe postpone the test & review.

**Comment by evaklopp** [comment]
@phillipoertel thanks for all your work. unfortunately I can´t open your first link to production, don´t know why. It seems like I´m not able to authenticate/log in or something. The second link to staging works. How can I test/see if the meters are labeled correctly?

**Comment by phillipoertel** [comment]
I added the “clean” links to groups you see above (using the slugs) only today, so they don’t work on production yet — I didn’t update production, we’re live now. 
Since we didn’t discuss yet when to do production updates, I decided to be “conservative”, even though it’s an internal tool. 

So for testing we have Staging.

**Comment by phillipoertel** [comment]
Same applies for the database, the production system does not yet show the newly assigned common consumption labels.

**Comment by evaklopp** [comment]
Yeah great job and very helpfull, closing the ticket.

**Comment by evaklopp** [comment]
https://buzzn-console-staging.herokuapp.com/admin/groups/gertrud-grunow-strasse: yes all common registers: "WEG Gem.raum"
https://buzzn-console-staging.herokuapp.com/admin/groups/huehnefeldstrasse yes all common registers: Heizung, Aufzug
https://buzzn-console-staging.herokuapp.com/admin/groups/reinmarplatz: yes all common registers: Heizzentrale, E-Tankstelle, UV Haustechnik, Antenne, Aufzug, Gem EG
https://buzzn-console-staging.herokuapp.com/admin/groups/karmensoeldnerstrasse: really no common register !
https://buzzn-console-staging.herokuapp.com/admin/groups/lindenstrasse: really no common register !
Am Urtlgraben: "privat" labeled register is private, but has reduced eeg. 
so reduced eeg is not a 100% rule that it is a common register and furthermore, there is also the possibility of a full eeg and common register. 
BK-data should be up to date according to PhO
