### ISSUE TITLE
Reliable downtime messages from New Relic

### ISSUE THREAD

**Issue by dottorer** [buzzn/scrum#92]
**User story**

As a developer
I want receive reliable downtime messages from New Relic
so that I can take action and avoid false positives.

---

**Definition of done**

- [x] research 2 hours what are the reasons for alerts/understanding the reasons

---

**Technical details**

_Backend_

- [x] maybe: disable the old, paid newrelic account --> disabled monitoring of staging, left production monitoring enabled as it monitors the backend for aws-core.buzzn.io, which is still used for display.buzzn.io.
- [x] investigate reasons why the alerts were triggered

**Comment by phillipoertel** [comment]
Here's a summary of the recent downtime alerts:

|source|deployment|when|reason|
|-------|------------|------|------|
|Heroku|core production| today| caused by maintenance mode being turned on for a few hours|
|Heroku|core staging|last Wed and Fri|two alerts, both were triggered while deployment was in process
|NewRelic|core staging| regularly during the last days |

**Comment by dottorer** [comment]
CLeanup of old NR logging completed. Account closed, final invoice paid. We only use Heroku NR now which closes this ticket successfully. Thanks @phillipoertel !
